/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ShopCategorySubRouteImport } from './routes/shop.$category.$sub'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads.$'
import { Route as ApiCatalogIdRouteImport } from './routes/api/catalog/$id'
import { Route as ApiCatalogIdStockRouteImport } from './routes/api/catalog/$id.stock'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySubRoute = ShopCategorySubRouteImport.update({
  id: '/shop/$category/$sub',
  path: '/shop/$category/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogIdRoute = ApiCatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCatalogRoute,
} as any)
const ApiCatalogIdStockRoute = ApiCatalogIdStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ApiCatalogIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog': typeof ApiCatalogRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/api/catalog/$id': typeof ApiCatalogIdRouteWithChildren
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/api/catalog/$id/stock': typeof ApiCatalogIdStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog': typeof ApiCatalogRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/api/catalog/$id': typeof ApiCatalogIdRouteWithChildren
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/api/catalog/$id/stock': typeof ApiCatalogIdStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/catalog': typeof ApiCatalogRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/product/$id': typeof ProductIdRoute
  '/api/catalog/$id': typeof ApiCatalogIdRouteWithChildren
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/api/catalog/$id/stock': typeof ApiCatalogIdStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/catalog'
    | '/api/upload'
    | '/product/$id'
    | '/api/catalog/$id'
    | '/api/uploads/$'
    | '/shop/$category/$sub'
    | '/api/catalog/$id/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/catalog'
    | '/api/upload'
    | '/product/$id'
    | '/api/catalog/$id'
    | '/api/uploads/$'
    | '/shop/$category/$sub'
    | '/api/catalog/$id/stock'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/catalog'
    | '/api/upload'
    | '/product/$id'
    | '/api/catalog/$id'
    | '/api/uploads/$'
    | '/shop/$category/$sub'
    | '/api/catalog/$id/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiCatalogRoute: typeof ApiCatalogRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
  ShopCategorySubRoute: typeof ShopCategorySubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/$sub': {
      id: '/shop/$category/$sub'
      path: '/shop/$category/$sub'
      fullPath: '/shop/$category/$sub'
      preLoaderRoute: typeof ShopCategorySubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/$id': {
      id: '/api/catalog/$id'
      path: '/$id'
      fullPath: '/api/catalog/$id'
      preLoaderRoute: typeof ApiCatalogIdRouteImport
      parentRoute: typeof ApiCatalogRoute
    }
    '/api/catalog/$id/stock': {
      id: '/api/catalog/$id/stock'
      path: '/stock'
      fullPath: '/api/catalog/$id/stock'
      preLoaderRoute: typeof ApiCatalogIdStockRouteImport
      parentRoute: typeof ApiCatalogIdRoute
    }
  }
}

interface ApiCatalogIdRouteChildren {
  ApiCatalogIdStockRoute: typeof ApiCatalogIdStockRoute
}

const ApiCatalogIdRouteChildren: ApiCatalogIdRouteChildren = {
  ApiCatalogIdStockRoute: ApiCatalogIdStockRoute,
}

const ApiCatalogIdRouteWithChildren = ApiCatalogIdRoute._addFileChildren(
  ApiCatalogIdRouteChildren,
)

interface ApiCatalogRouteChildren {
  ApiCatalogIdRoute: typeof ApiCatalogIdRouteWithChildren
}

const ApiCatalogRouteChildren: ApiCatalogRouteChildren = {
  ApiCatalogIdRoute: ApiCatalogIdRouteWithChildren,
}

const ApiCatalogRouteWithChildren = ApiCatalogRoute._addFileChildren(
  ApiCatalogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiCatalogRoute: ApiCatalogRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ProductIdRoute: ProductIdRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
  ShopCategorySubRoute: ShopCategorySubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
